name = "WonderTech"
author = "Stewart Borle"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b0145e1eae39dc894d2bead23eca9a48508f6d8448af8084b981b553c8d92ac"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
