name = "WonderTech"
author = "Stewart Borle"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ab3f45fbfb8a68d2d4e1bff9b279e623431caeb0b1c8ade280266289daace73"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
