name = "WonderTech"
author = "Stewart Borle"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69fb3503ccc0e6def260dfdf2586092447b15d9556c7c5d10c41208a5ebc5e72"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
