name = "WonderTech"
author = "Stewart Borle"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9449ef4721e93abfe035235f023a60e89942bfa7d9ba1e650ebed0d47076948b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
