name = "WonderTech"
author = "Stewart Borle"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1369dd5b0925b94b98aaa87199e39d319c113f1a6cba70f78d1a930432b0ee3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
