name = "WonderTech"
author = "Stewart Borle"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f88d2a614701a788ac2629de59a00ce90b4c7dc90b3776b6e97ed0c8acca8358"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
