name = "WonderTech"
author = "Stewart Borle"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad79db61c5926f39b3f78dc392ec7a827f9b0ecc08dd932c7b225fc7b93a45e1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
