name = "WonderTech"
author = "Stewart Borle"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5816e5424dce2a75334921e61c2820a89313d76d741304d56330807828bc8368"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
