name = "WonderTech"
author = "Stewart Borle"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90572d785f0c61e5547204cd86f9ddf3884343da3d416b5ea07ccc45163a3872"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.96"

[options]
datapack-folder = "config/paxi/datapacks"
