name = "WonderTech"
author = "Stewart Borle"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f28f05a8113d1a327d9b235db8bf5ebe5f3972a07510a7bea80d478e612444d3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
