name = "WonderTech"
author = "Stewart Borle"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e37c3508c6fb0b229fbf18e63b4cb16dcc3329646822558dbdd6af99bbdea49"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
