name = "WonderTech"
author = "Stewart Borle"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca0ba60dfc7700de70c0bbefde8bffd980cfde69dcfcf9e2938ad7001336821d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
