name = "WonderTech"
author = "Stewart Borle"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3939ed654570cb522683ba8a1599d07ae66ae208c0eb4237170d5a7a7bfec537"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
