name = "WonderTech"
author = "Stewart Borle"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46276781761e235f0039bd582a7f8363bf60fdbe76c85635eab7548f078a43bd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
