name = "WonderTech"
author = "Stewart Borle"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a725e6e998478e56128ab2cba193e7f28d98d51bbab36e3f8122f54c6e0070a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
