name = "WonderTech"
author = "Stewart Borle"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9461ad4eba6033db3a056253a11e1d65a0fb73728838a00ecd252e81ec6625a9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
