name = "WonderTech"
author = "Stewart Borle"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08db384011d068d1a7a03965a4389e579b1e21464e7c8902cf03db55f09dfc1d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
