name = "WonderTech"
author = "Stewart Borle"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6497d5548c87382b7dbad9371274fee323f052b81b89e295d09d5d68f22cd3cd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
