name = "WonderTech"
author = "Stewart Borle"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "309f1556da1ad476ddf20373ad5364c7502e4790c44fb23a1757a2e02fbfa5e3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
