name = "WonderTech"
author = "Stewart Borle"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be060a7f5a5e8b9ace76f85eca378354feca3047a482a4b1b2562007d819f986"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
