name = "WonderTech"
author = "Stewart Borle"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cae52fa41125b4150e5ce1bd0e0ee50c87a33d2e53fb6ff95531cfce5ca4452"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
