name = "WonderTech"
author = "Stewart Borle"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87894aeb32a4074c003fcfe28ba832e54069b218279b804c68651930c4d772e7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"

[options]
datapack-folder = "config/paxi/datapacks"
