name = "WonderTech"
author = "Stewart Borle"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b6e04890edf975669d61a02dc1c1ecc0fb8de0f1558aa9811f0502a3ba6c1d8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.96"

[options]
datapack-folder = "config/paxi/datapacks"
